### ISSUE TITLE
[Feature] 일정의 담은 Spot 조회 기능 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#110]
### ✏️Describe
- 일정의 담은 Spot 조회 기능 구현

### 🚀Task
- [x] 일정의 담은 Spot 관련 SuccessCode 추가
- [x] 일정의 담은 Spot DTO 작성
- [x] SelectedSpotRepository에 findAllBySchedule 작성
- [x] 일정의 담은 Spot 조회 기능 구현
- [x] 담은 Spot (SelectedSpot) Entity 작성
- [x] 일정의 담은 Spot 조회 기능 url 매핑
