### ISSUE TITLE
[Feature] 일정에 Spot 담기 기능 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#124]
### ✏️Describe
- 일정에 Spot 담기 기능 구현

### 🚀Task
- [x] SelectedSpotRequest DTO 작성
- [x] 일정에 Spot 담기 기능 구현
- [x] 일정에 Spot 담기 기능 url 매핑
