### ISSUE TITLE
[Feature] API spec 변경에 따른 '대표 이미지 수정 API' 변경 부분 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#125]
### ✏️Describe
- API spec 변경에 따른 '대표 이미지 수정 API' 변경 부분 구현
- 대표 이미지 생성 API와 동일하게 맞추어 달라는 추가 요구사항에 따라, API spec이 변경됨.
- 따라서, 이에 맞추어 Request 매핑 변경 부분 추가 구현

### 🚀Task
- [x] RepresentativeImageRepository에 findByRegion 작성
- [x] Request 매핑 변경 부분 변경에 따른 비즈니스 로직 변경
- [x] Request 매핑 변경 부분 추가 구현
