### ISSUE TITLE
[Feature] API spec 변경에 따른 '여행 기록 이미지 수정 API' 변경 기능 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#130]
### ✏️Describe
- API spec 변경에 따른 '여행 기록 이미지 수정 API' 변경 기능 구현
- deleteImages를 id가 아닌 imageUrl로 변경해달라는 요청을 받아, 이에 맞춰 수정

### 🚀Task
- [x] RecordUpdateRequest의 deleteImages Type을 String으로 변경
- [x] RecordImageRepository에 existsByUrl, deleteByUrl 추가 작성
- [x] 여행 기록 이미지 수정 기능 호출 메서드 변경
