### ISSUE TITLE
[Refactor] Record, RecordImage Entity 수정

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#14]
### ✏️Describe
Record, RecordImage Entity에 Builder 패턴 적용
Image 객체의 멤버 변수이므로 image라는 명칭이 중복 사용되는 것을 개선하기 위해 RecordImage Entity의 imageUrl 칼럼명을 url로 변경

### 🚀Task
- [x] Record Entity Builder 패턴 적용
- [x] RecordImage Entity Builder 패턴 적용
- [x] RecordImage Entity의 imageUrl 칼럼명을 url로 변경
