### ISSUE TITLE
[Feature] User 도메인 profileLevel 필드 추가 및 등급 업데이트 메소드 구현

### ISSUE THREAD

**Issue by Jeongmin39** [TRIP-SPOT/SPOT-Server#168]
### ✏️Describe
User 도메인 profileLevel 필드 추가 및 등급 업데이트 메소드 구현

### 🚀Task
- [ ] ProfileLevel Enum 작성
- [ ] User 도메인 ProfileLevel 필드 추가
- [ ] updateProfileLevel 메소드 구현
