### ISSUE TITLE
[Refactor] Badge를 Region 단위에서 City 단위로 수정

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#173]
### ✏️Describe
- 추가 요구사항에 따라, 기능을 수정하기 위해 Badge를 Region 단위에서 City 단위로 수정
- 이에 따라, Badge의 `count` 칼럼 삭제 및 User의 `getBadgeCount()` 삭제
- Badge의 기존 칼럼들을 사용하던 기능을 변경에 맞춰 수정

### 🚀Task
- [x] Badge, User Entity 수정
- [x] 기존 회원 등급 업데이트 기능 수정
- [x] 기존 퀴즈 정답 시, Badge 부여 기능 수정
