### ISSUE TITLE
[Bug] Record 도메인 User 필터링 누락 오류

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#175]
### ✏️Describe
- Record 대표 이미지 User 필터링 누락 오류 수정
- 지역 별 Record 조회 User 필터링 누락 오류 수정

### 🚀Task
- [x] Record 도메인 Repository의 쿼리 메서드에 ByUser 추가
- [x] 대표 이미지 수정 로직의 사용 쿼리 메서드 수정
- [x] 지역별 Record 조회 로직의 사용 쿼리 메서드 수정
- [x] RecordController의 대표 이미지 수정, 지역별 Record 조회 메서드에 @currentuser 추가
