### ISSUE TITLE
[Feature] 뱃지 생성 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#178]
### ✏️Describe
- 카메라 필터 사용 시, 뱃지 생성 기능을 위한 뱃지 생성 API 구현

### 🚀Task
- [x] 뱃지 획득 경로 타입 enum 생성 및 Entity에 추가
- [x] Badge 생성 로직 BadgeService로 분리
- [x] BadgeRequest DTO 작성
- [x] 뱃지 생성 API 구현
- [x] Badge 패키지 별도 분리
