### ISSUE TITLE
[Feature] Badge 도메인 분리에 따른 기존 로직 변경

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#182]
### ✏️Describe
- Record, Quiz를 통한 뱃지 생성 로직 구현

### 🚀Task
- [x] Record 뱃지 생성 로직 구현
- [x] Quiz 뱃지 생성 로직 구현
- [x] User Entity의 getCount 삭제 및 이에 따른 로직 변경
