### ISSUE TITLE
[Feature] 지역 별 Record(여행 기록) 조회 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#3]
### ✏️Describe
지역 별 Record(여행 기록) 조회 API 구현
지역 정보를 경로 변수로 받아, 일치하는 모든 Record(여행 기록) 조회

### ✏️Describe
지역 별 Record(여행 기록) 조회 API 구현
지역 정보를 경로 변수로 받아, 일치하는 모든 Record(여행 기록) 조회

### 🚀Task
- [x] 지역 별 record 조회 Success Code 추가
- [x] RecordImageRepository에 썸네일 이미지 조회 기능 추가
- [x] RecordRepository에 지역 별 record 조회 기능 추가
- [x] RecordImageService에 썸네일 이미지 조회 기능 추가
- [x] RecordService에서 지역 별 record 조회 및 썸네일 조회 기능 구현
- [x] RegionalRecordResponse DTO 구현
- [x] RecordController 지역 별 records 조회 기능 구현
