### ISSUE TITLE
[Feature] Record(여행 기록) 생성 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#34]
### ✏️Describe
Record(여행 기록) 생성 API 구현
RecordImage와 Record 데이터를 multipart로 구분하여 전달 받는다.
이후, 각 service의 로직을 통해 Entity 객체 생성 및 저장을 수행한다.

### 🚀Task
- [x] 좋아요 Entity 이름 Likes로 수정 (예약어)
- [x] Region, City enum 작성
- [x] RecordImage Entity 추가
- [x] 여행 기록 생성 SuccessCode 추가
- [x] multipart 설정 추가
- [x] RecordImageRepository 추가
- [x] Record 생성을 위한 Request, Response DTO 구현
- [x] 이미지 저장 후, RecordImage 저장 기능 구현
- [x] Record 저장 및 RecordImage 생성 호출 기능 구현
- [x] RecordController 구현
