### ISSUE TITLE
[Feature] 특정 Record(여행 기록) 상세 정보 조회 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#4]
### ✏️Describe
특정 Record(여행 기록) 상세 정보 조회 API 구현
Record Id를 경로 변수로 받아, 해당 Record(여행 기록)의 상세 정보 조회

### 🚀Task
- [x] 특정 Record에 포함된 이미지 조회 기능 구현
- [x] 단일 Record 조회 기능 구현
- [x] 지역 별 조회 API 와 겹치지 않게 url 매핑
