### ISSUE TITLE
[Feature] Record(여행 기록) 수정 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#5]
### ✏️Describe
Record (여행 기록) 수정 API 구현
- Record Id를 경로 변수로 받아, 해당 Record를 식별
- 이름, 설명을 Request body로 받아, 식별한 Record 수정하여 저장
- 삭제된 RecordImage는 식별자를 Reqeust body로 받아, 삭제 수행
- 추가된 RecordImage는 파일을 별도 part로 받아, 추가 수행 

### 🚀Task
- [x] recordImage 삭제 기능 구현
- [x] RecordService에 updateRecord 기능 추가
- [x] deleteImage -> deleteRecordImage로 네이밍 변경
- [x] RecordUpdateRequest DTO 작성
- [x] 여행 기록 Success Code 추가
- [x] Record Entity에 수정 가능 칼럼의 update 메서드 추가
- [x] RecordContorller에 updateRecord 기능 추가
