### ISSUE TITLE
[Feature] 대표 이미지 전체 조회 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#52]
### ✏️Describe
특정 User의 모든 대표 이미지를 조회하는 API

### 🚀Task
- [x] 대표 이미지 전체 조회 기능 구현
- [x] RepresentativeImageResponse DTO에 id 추가
- [x] 대표 이미지 전체 조회 API url 매핑
