### ISSUE TITLE
[Feature] 퀴즈 조회 기능 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#55]
### ✏️Describe
- id로 해당 퀴즈 조회하는 기능 구현
- 정답을 제외한 나머지 데이터 반환

### 🚀Task
- [x] Quiz Entity 추가 요구 사항에 맞게 변경
- [x] QuizResponse DTO 작성
- [x] 퀴즈 조회 기능 구현
- [x] 퀴즈 조회 기능 url 매핑
