### ISSUE TITLE
[Feature] 퀴즈 정답 확인 기능 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#57]
### ✏️Describe
- 답변을 받아, 정답인지 여부를 반환
- 내부적으로 사용자에 뱃지 생성 로직 수행

### 🚀Task
- [x] 정답 확인 DTO 작성
- [x] 정답 맞춘 경우, 뱃지 생성 기능 구현
- [x] 퀴즈 정답 확인 기능 url 매핑
- [x] Badge Entity 뱃지 추가 로직 구현
- [x] Quiz Entity 퀴 정답 확인 로직 구현
- [x] BadgeRepository findAllByUserAndRegion 인터페이스 작성
- [x] QuizController SuccessCode 적용
