### ISSUE TITLE
[Feature] Record(여행 기록) 삭제 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#6]
### ✏️Describe
Record (여행 기록) 삭제 API 구현
Record Id를 경로 변수로 받아, 해당 Record와 연관된 RecordImage 삭제

### 🚀Task
- [x] Record에 연관된 Record 이미지 삭제 기능 구현
- [x] RecordImageRespository에 deleteAllByRecord 추가
- [x] Record 삭제 및 연관 RecordImage 삭제 위임 로직 구현
- [x] 여행 기록 삭제 Success Code 추가
- [x] RecordController 삭제 기능 매핑
