### ISSUE TITLE
[Feature] 현재 위치 기준 반경 20km 이내 촬영지 검색 기능 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#63]
### ✏️Describe
- 현재 위치를 위,경도 값으로 받아, 반경 20km 이내 촬영지 검색하는 기능

### 🚀Task
- [x] 위,경도 비교하여 반경 20km 이내인지 여부 판단 기능 구현 
- [x] Spot, Work Entity Getter 및 생성자 추가 
- [x] AccessibleSpotResponse DTO 작성 
- [x] 반경 20km 이내 스팟 조회 기능 url 매핑 및 SuccessCode 추가
- [x] AccessibleSpotResponse dto/response로 이동
