### ISSUE TITLE
[Feature] Record (여행 기록)의 대표 이미지 생성 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#7]
### ✏️Describe
Record (여행 기록)의 대표 이미지 생성 API 구현

### 🚀Task
- [x] 대표 이미지 Success Code 추가
- [x] 대표 이미지 Entity 작성
- [x] 대표 이미지 DTO 작성
- [x] RepresentativeImageRepository 생성
- [x] 대표 이미지 생성 로직 구현
- [x] 대표 이미지 생성 url 매핑
