### ISSUE TITLE
[Feature] 여행 일정 생성 기능 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#74]
### ✏️Describe
- 여행 일정 생성 기능 구현

### 🚀Task
- [x] Schedule SuccessCode 추가
- [x] Schedule 생성을 위한 DTO 작성
- [x] Schedule Entity 세팅
- [x] Schedule 생성 기능 구현
- [x] Schedule 생성 기능 url 매핑
