### ISSUE TITLE
[Feature] 대표 이미지 수정 API 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#8]
### ✏️Describe
대표 이미지 수정 API 구현

### 🚀Task
- [x] 대표 이미지 수정 기능 구현
- [x] RepresentativeImage Entity에 updateUrl 메서드 추가
- [x] 대표 이미지 수정 기능 url 매핑
