### ISSUE TITLE
[Feature] 여행 일정 목록 조회 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#82]
### ✏️Describe
- 여행 일정 목록 조회 구현

### 🚀Task
- [x] 일정 조회를 위해 DTO에 id field 추가
- [x] ScheduleRepository에 findAllByUser 추가
- [x] 여행 일정 목록 조회 기능 구현
- [x] 여행 일정 목록 조회 url 매핑
