### ISSUE TITLE
[Feature] 여행 일정에 장소 추가 기능 구현

### ISSUE THREAD

**Issue by yangchef1** [TRIP-SPOT/SPOT-Server#99]
### ✏️Describe
- 여행 일정에 장소 추가 기능 구현

### 🚀Task
- [x] 여행 일정에 장소 추가 DTO 작성
- [x] LocationRepository day, seq 계산을 위한 메서드 추가
- [x] Location Entity 필드 변경
- [x] 여행 일정에 장소 추가 기능 구현
- [x] 여행 일정에 장소 추가 url 매핑
